@TicketApi_HostAddress = https://localhost:7154

GET {{TicketApi_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{TicketApi_HostAddress}}/api/ticket
Content-Type: application/json

{
  //Contact
}

###

GET {{TicketApi_HostAddress}}/api/ticket/kjkhj/

###
